name: Auto approve
on: pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: >-
          github.actor == 'arlac77'
          ||Â github.actor == 'dependabot[bot]'
          || github.actor == 'dependabot-preview[bot]'
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
