name: Auto approve
'on': pull_request
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.4.0
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
