name: API to readme
'on':
  schedule:
    - cron: 31 14 * * 6
jobs:
  update_readme_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.11.0
      - run: npm ci
      - run: npm run docs
      - uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: README.md
          title: Sync API into README
          branch: readme-api
          commit-message: 'docs(README): sync API'
