name: API to readme
on:
  schedule:
    - cron: 31 14 * * 6
  push:
    paths:
      - src/*
jobs:
  update_readme_api:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: prepare node
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 22.13.1
      - name: install
        run: npm ci
      - name: run docs
        run: npm run docs
      - uses: gr2m/create-or-update-pull-request-action@v1.10.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: README.md
          title: Sync API into README
          branch: readme-api
          commit-message: "docs(README): sync API"
